import 'package:ds_milk_world_client/ds_milk_world_client.dart';

class MockData {
  static final Outlet outlet = Outlet(
    name: 'DS Milk World',
    phone: '+91 866 254 9999',
    address: 'Near Auto Nagar Gate, Bandar Road, Auto Nagar, Vijayawada, AP 520007',
    latitude: 16.4950,
    longitude: 80.6650,
    status: 'open',
    serviceRadiusM: 5000,
    timezone: 'Asia/Kolkata',
    openingTime: '10:00',
    closingTime: '23:00',
    minOrderPaise: 0,
  );

  static final List<Category> categories = [
    Category(name: 'Falooda', slug: 'falooda', sortOrder: 1, published: true),
    Category(name: 'Our Specials', slug: 'our-specials', sortOrder: 2, published: true),
    Category(name: 'Thick Shakes', slug: 'thick-shakes', sortOrder: 3, published: true),
    Category(name: 'Butter Milk', slug: 'butter-milk', sortOrder: 4, published: true),
    Category(name: 'Milk Shakes', slug: 'milk-shakes', sortOrder: 5, published: true),
    Category(name: 'Soda', slug: 'soda', sortOrder: 6, published: true),
    Category(name: 'Lassi', slug: 'lassi', sortOrder: 7, published: true),
    Category(name: 'Mocktails', slug: 'mocktails', sortOrder: 8, published: true),
  ];

  static final List<Product> products = [
    Product(
      sku: 'DSMW-001',
      categoryName: 'Falooda',
      name: 'Oreo Falooda',
      shortDescription: 'Indulge in a delectable falooda loaded with delightful flavors and a crunchy surprise.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 1,
    ),
    Product(
      sku: 'DSMW-002',
      categoryName: 'Falooda',
      name: 'Rose Falooda',
      shortDescription: 'A delightful and refreshing treat bursting with vibrant flavors and sweet aromas.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 2,
    ),
    Product(
      sku: 'DSMW-003',
      categoryName: 'Falooda',
      name: 'Badam Falooda',
      shortDescription: 'Indulge in the lusciously creamy and delightful blend of flavors found in this scrumptious Badam Falooda.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 18000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 3,
    ),
    Product(
      sku: 'DSMW-004',
      categoryName: 'Falooda',
      name: 'Dry Fruit Falooda',
      shortDescription: 'Traditionally it is made by mixing rose syrup, vermicelli, and sweet basil seeds with milk, often served with ice cream and dry fruits.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 18000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 4,
    ),
    Product(
      sku: 'DSMW-005',
      categoryName: 'Falooda',
      name: 'Chocolate Falooda',
      shortDescription: 'A delectable vegetarian treat featuring rich chocolate flavors and creamy textures, the Chocolate Falooda is a must-try dessert experience.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 5,
    ),
    Product(
      sku: 'DSMW-006',
      categoryName: 'Falooda',
      name: 'Pista Falooda',
      shortDescription: 'A delightful veg creation in the Falooda category, enticing with its mouthwatering flavors and rich textures.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 6,
    ),
    Product(
      sku: 'DSMW-007',
      categoryName: 'Falooda',
      name: 'Fruit Punch Falooda',
      shortDescription: 'A refreshing and delightful fusion of flavors, blending fruits and traditional falooda for a delightful sweet treat.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 18000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 7,
    ),
    Product(
      sku: 'DSMW-008',
      categoryName: 'Falooda',
      name: 'Kulfi Falooda',
      shortDescription: 'A delightful and refreshing Indian dessert bursting with flavors and textures, perfect for a sweet treat.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 18000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 8,
    ),
    Product(
      sku: 'DSMW-009',
      categoryName: 'Falooda',
      name: 'Mango Falooda',
      shortDescription: 'A delightful blend of refreshing flavors, this indulgent dessert is a perfect combination of creamy, sweet, and fruity goodness.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 9,
    ),
    Product(
      sku: 'DSMW-010',
      categoryName: 'Our Specials',
      name: 'Fruit Punch',
      shortDescription: 'A refreshing blend of vibrant fruits that bursts with sweet and tangy flavors to invigorate your taste buds.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 10,
    ),
    Product(
      sku: 'DSMW-011',
      categoryName: 'Our Specials',
      name: 'Organic Sapota Juice',
      shortDescription: 'Made of pure organic sapota grown in our own garden',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 11,
    ),
    Product(
      sku: 'DSMW-012',
      categoryName: 'Our Specials',
      name: 'Lemonade',
      shortDescription: 'Refreshing and citrusy, this zesty creation will quench your thirst and leave you feeling rejuvenated.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 3500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 12,
    ),
    Product(
      sku: 'DSMW-013',
      categoryName: 'Our Specials',
      name: 'Badam Milk',
      shortDescription: 'Indulge in a creamy and fragrant delight with our special Badam Milk.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 13,
    ),
    Product(
      sku: 'DSMW-014',
      categoryName: 'Our Specials',
      name: 'Pulpy Grape',
      shortDescription: 'A luscious and refreshing creation bursting with natural fruit flavors, perfect for those seeking a delightful vegetarian option from our specials.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 14,
    ),
    Product(
      sku: 'DSMW-015',
      categoryName: 'Our Specials',
      name: 'Rose Milk',
      shortDescription: 'A luscious and refreshing treat of creamy and aromatic rose-infused milk, indulging the senses with its delicate flavors.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 15,
    ),
    Product(
      sku: 'DSMW-016',
      categoryName: 'Our Specials',
      name: 'Pista Milk',
      shortDescription: 'Creamy and aromatic, our special is a delectable blend of smooth milk and rich pistachios that will leave your taste buds wanting more.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 16,
    ),
    Product(
      sku: 'DSMW-017',
      categoryName: 'Our Specials',
      name: 'Badam Milk (500 ml)',
      shortDescription: 'Indulge in the rich and creamy flavors of our special Badam Milk.',
      sizeOrServing: '500 ml',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 17,
    ),
    Product(
      sku: 'DSMW-018',
      categoryName: 'Our Specials',
      name: 'Badam Milk (1000 ml)',
      shortDescription: 'Indulge in the creamy goodness of Our Specials - a delectable, velvety treat infused with the rich flavors of almond and milk.',
      sizeOrServing: '1000 ml',
      pricePaise: 27000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 18,
    ),
    Product(
      sku: 'DSMW-019',
      categoryName: 'Our Specials',
      name: 'Pulpy Grape ( 500 ml)',
      shortDescription: 'Indulge in the refreshing burst of Pulpy Grape, a luscious and unique addition to our Specials lineup!',
      sizeOrServing: '500 ml',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 19,
    ),
    Product(
      sku: 'DSMW-020',
      categoryName: 'Our Specials',
      name: 'Pulpy Grape ( 1000 ml)',
      shortDescription: 'Indulge in the refreshing blend of juicy and luscious grapes bursting with natural pulpy goodness in our Veg Specials.',
      sizeOrServing: '1000 ml',
      pricePaise: 20000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 20,
    ),
    Product(
      sku: 'DSMW-021',
      categoryName: 'Our Specials',
      name: 'Cold Coffee',
      shortDescription: 'A refreshing and creamy treat perfect for any time of the day.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 21,
    ),
    Product(
      sku: 'DSMW-022',
      categoryName: 'Thick Shakes',
      name: 'Dry Fruit Thick Shake',
      shortDescription: 'Indulge in a luscious thick shake packed with the rich flavors of assorted dry fruits, a treat for all the senses.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 25000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 22,
    ),
    Product(
      sku: 'DSMW-023',
      categoryName: 'Thick Shakes',
      name: 'Caramel Oreo Thick Shake',
      shortDescription: 'Indulge in a decadent blend of creamy caramel and irresistible Oreo cookies with our deliciously rich Thick Shake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 24000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 23,
    ),
    Product(
      sku: 'DSMW-024',
      categoryName: 'Thick Shakes',
      name: 'Gems Thick Shake',
      shortDescription: 'Indulge in a luscious and creamy thick shake that will leave you craving for more.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 22000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 24,
    ),
    Product(
      sku: 'DSMW-025',
      categoryName: 'Thick Shakes',
      name: 'Choco Chips Thick Shake',
      shortDescription: 'Indulge in a creamy and irresistible thick shake loaded with delectable choco chips.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 26000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 25,
    ),
    Product(
      sku: 'DSMW-026',
      categoryName: 'Thick Shakes',
      name: 'Munch Thick Shake',
      shortDescription: 'Indulge in the creamy richness of our Munch Thick Shake, a veggie delight that will satisfy your sweet cravings in one sip.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 26,
    ),
    Product(
      sku: 'DSMW-027',
      categoryName: 'Thick Shakes',
      name: 'Bourbon Thick Shake',
      shortDescription: 'Indulge in a rich and creamy Thick Shake that combines the smoothness of bourbon to create a delectable veggie delight.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 27,
    ),
    Product(
      sku: 'DSMW-028',
      categoryName: 'Thick Shakes',
      name: 'Perk Thick Shake',
      shortDescription: 'Indulge in a rich and creamy delight that will leave you craving for more-packed with irresistible flavors.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 28,
    ),
    Product(
      sku: 'DSMW-029',
      categoryName: 'Thick Shakes',
      name: 'Dark Fantasy Thick Shake',
      shortDescription: 'Indulge in a rich and decadent treat that will take your taste buds on a dark and velvety adventure.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 29,
    ),
    Product(
      sku: 'DSMW-030',
      categoryName: 'Thick Shakes',
      name: 'Kitkat Thick Shake',
      shortDescription: 'Indulge in a creamy and luscious delight bursting with the irresistible flavors of Kitkat.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 30,
    ),
    Product(
      sku: 'DSMW-031',
      categoryName: 'Thick Shakes',
      name: 'Oreo Thick Shake',
      shortDescription: 'Indulge in a creamy and luscious dessert that will satisfy all your sweet cravings.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 31,
    ),
    Product(
      sku: 'DSMW-032',
      categoryName: 'Thick Shakes',
      name: 'Caramel Thick Shake',
      shortDescription: 'Indulge in a decadently sweet and creamy caramel delight that will leave you craving for more.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 24000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 32,
    ),
    Product(
      sku: 'DSMW-033',
      categoryName: 'Thick Shakes',
      name: 'Pista Thick Shake',
      shortDescription: 'Indulge in a luscious, creamy and irresistible thick shake delicately flavored with pistachio essence.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 33,
    ),
    Product(
      sku: 'DSMW-034',
      categoryName: 'Thick Shakes',
      name: 'Butter Choco Thick Shake',
      shortDescription: 'Indulge in a luscious and rich blend of butter and chocolate, creating a decadent thick shake that will satisfy all your dessert cravings.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 34,
    ),
    Product(
      sku: 'DSMW-035',
      categoryName: 'Thick Shakes',
      name: 'Choco Fun Thick Shake',
      shortDescription: 'Indulge in a lusciously creamy and delightful thick shake that will satisfy your chocolate cravings.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 35,
    ),
    Product(
      sku: 'DSMW-036',
      categoryName: 'Thick Shakes',
      name: 'Yummy Butterscotch Thick Shake',
      shortDescription: 'Indulge in the delectable flavors of a luscious butterscotch thick shake that is sure to satisfy your sweet tooth.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 36,
    ),
    Product(
      sku: 'DSMW-037',
      categoryName: 'Thick Shakes',
      name: 'Mango Melody Thick Shake',
      shortDescription: 'A luscious and tropical delight, blending the rich sweetness of mangoes into a delightful thick shake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 21000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 37,
    ),
    Product(
      sku: 'DSMW-038',
      categoryName: 'Thick Shakes',
      name: 'Strawberry Thick Shake',
      shortDescription: 'Indulge in the lusciousness of this creamy and fruity delight that refreshes and satisfies your taste buds.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 19000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 38,
    ),
    Product(
      sku: 'DSMW-039',
      categoryName: 'Thick Shakes',
      name: 'Vanilla Thick Shake',
      shortDescription: 'Indulge in a creamy and luxurious taste experience with this delectable Vanilla Thick Shake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 19000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 39,
    ),
    Product(
      sku: 'DSMW-040',
      categoryName: 'Butter Milk',
      name: 'Masala Buttermilk',
      shortDescription: 'A refreshing and flavorful traditional Indian beverage that will tantalize your taste buds with its unique blend of aromatic spices.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 3000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 40,
    ),
    Product(
      sku: 'DSMW-041',
      categoryName: 'Butter Milk',
      name: 'Special Lemon Masala',
      shortDescription: 'A refreshing blend of tangy lemon and aromatic masala, harmoniously combined to create a tantalizing flavor experience.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 3000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 41,
    ),
    Product(
      sku: 'DSMW-042',
      categoryName: 'Butter Milk',
      name: 'Special Jeera Masala',
      shortDescription: 'A refreshing and flavorful blend of aromatic spices, bringing a unique twist to classic buttermilk.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 42,
    ),
    Product(
      sku: 'DSMW-043',
      categoryName: 'Butter Milk',
      name: 'Sp.lemon Sabja Butter Milk',
      shortDescription: 'A refreshing blend of lemon and sabja seeds, this butter milk delivers a burst of tangy flavors, perfect to quench your thirst and tantalize your taste buds.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 4500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 43,
    ),
    Product(
      sku: 'DSMW-044',
      categoryName: 'Butter Milk',
      name: 'Sp Jeera Sabja Butter Milk',
      shortDescription: 'A refreshing and flavorful blend of jeera and sabja in creamy butter milk.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 4500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 44,
    ),
    Product(
      sku: 'DSMW-045',
      categoryName: 'Milk Shakes',
      name: 'Caramel Oreo Milkshake',
      shortDescription: 'Rich and creamy milkshake with a delicious caramel twist, topped with chunks of Oreo cookies.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 17000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 45,
    ),
    Product(
      sku: 'DSMW-046',
      categoryName: 'Milk Shakes',
      name: 'Golden Glory Milk Shake',
      shortDescription: 'Indulge in the irresistible creaminess of this luscious golden delight, a delectable milkshake that promises pure bliss with every sip.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11900,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 46,
    ),
    Product(
      sku: 'DSMW-047',
      categoryName: 'Milk Shakes',
      name: 'Sleek Strawberry Milk Shake',
      shortDescription: 'Indulge in a creamy and refreshing strawberry milkshake that will satisfy your sweet tooth.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 12000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 47,
    ),
    Product(
      sku: 'DSMW-048',
      categoryName: 'Milk Shakes',
      name: 'Black Shock Milk Shake',
      shortDescription: 'Indulge in a delightfully rich and velvety milkshake that blends bold flavors for a truly memorable experience.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 48,
    ),
    Product(
      sku: 'DSMW-049',
      categoryName: 'Milk Shakes',
      name: 'Mango Melody Milk Shake',
      shortDescription: 'A luscious melody of mango goodness blended into a creamy, refreshing milkshake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 49,
    ),
    Product(
      sku: 'DSMW-050',
      categoryName: 'Milk Shakes',
      name: 'Yummy Butterscotch Milk Shake',
      shortDescription: 'Indulge in the lusciousness of a delectable butterscotch milk shake, loaded with sweet and creamy flavors.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 50,
    ),
    Product(
      sku: 'DSMW-051',
      categoryName: 'Milk Shakes',
      name: 'Choco Fun Milk Shake',
      shortDescription: 'Indulge in a delightful milkshake that combines the richness of chocolate with the fun flavors of Choco Fun Milk Shake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 51,
    ),
    Product(
      sku: 'DSMW-052',
      categoryName: 'Milk Shakes',
      name: 'Butter Choco Milk Shake',
      shortDescription: 'Indulge your taste buds with a luscious and creamy blend of butter, chocolate, and milk in this delightful milkshake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 52,
    ),
    Product(
      sku: 'DSMW-053',
      categoryName: 'Milk Shakes',
      name: 'Pista Milk Shake',
      shortDescription: 'Indulge in the creamy and nutty goodness of this irresistible milkshake that will leave your taste buds craving for more.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 53,
    ),
    Product(
      sku: 'DSMW-054',
      categoryName: 'Milk Shakes',
      name: 'Caramel Milk Shake',
      shortDescription: 'Indulge in a delightful blend of creamy sweetness with our luscious Caramel Milk Shake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 54,
    ),
    Product(
      sku: 'DSMW-055',
      categoryName: 'Milk Shakes',
      name: 'Oreo Milk Shake',
      shortDescription: 'Indulge in a luscious, velvety treat that combines the rich, classic flavors of Oreo cookies with creamy milk for a satisfying Milk Shake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 55,
    ),
    Product(
      sku: 'DSMW-056',
      categoryName: 'Milk Shakes',
      name: 'Dark Fantasy Milk Shake',
      shortDescription: 'Indulge in the lusciousness of our rich and velvety milkshake, a decadent delight for all milkshake enthusiasts.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 56,
    ),
    Product(
      sku: 'DSMW-057',
      categoryName: 'Milk Shakes',
      name: 'Perk Milk Shake',
      shortDescription: 'Indulge in a refreshing and creamy milkshake that will perk up your taste buds.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 57,
    ),
    Product(
      sku: 'DSMW-058',
      categoryName: 'Milk Shakes',
      name: 'Bourbon Milk Shake',
      shortDescription: 'Indulge in a creamy and rich delight that perfectly blends the smoothness of milk with the flavors of decadent bourbon.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 58,
    ),
    Product(
      sku: 'DSMW-059',
      categoryName: 'Milk Shakes',
      name: 'Munch Milk Shake',
      shortDescription: 'Indulge in a creamy and delightful milkshake that will satisfy all your cravings with its luscious and irresistible flavors.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 59,
    ),
    Product(
      sku: 'DSMW-060',
      categoryName: 'Milk Shakes',
      name: 'Kitkat Milk Shake',
      shortDescription: 'A mouthwatering milkshake infused with the irresistible flavors of Kitkat.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 16000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 60,
    ),
    Product(
      sku: 'DSMW-061',
      categoryName: 'Milk Shakes',
      name: 'Choco Chip Milk Shake',
      shortDescription: 'Indulge in a luscious blend of creamy milk and rich chocolate chips with our Choco Chip Milk Shake.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 17000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 61,
    ),
    Product(
      sku: 'DSMW-062',
      categoryName: 'Soda',
      name: 'Sweet And Lime',
      shortDescription: 'A refreshing lime soda with a hint of sweetness, perfect for beating the heat.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 62,
    ),
    Product(
      sku: 'DSMW-063',
      categoryName: 'Soda',
      name: 'Salt And Lime Soda',
      shortDescription: 'Cool and refreshing lime soda with a hint of salt, perfect for beating the heat.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 63,
    ),
    Product(
      sku: 'DSMW-064',
      categoryName: 'Soda',
      name: 'Cola Soda',
      shortDescription: 'A refreshing and bubbly concoction that\'s perfect for quenching your thirst and indulging in a delightful burst of flavors.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 64,
    ),
    Product(
      sku: 'DSMW-065',
      categoryName: 'Soda',
      name: 'Orange Soda',
      shortDescription: 'A refreshing and citrusy delight that perfectly captures the essence of tangy oranges.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 65,
    ),
    Product(
      sku: 'DSMW-066',
      categoryName: 'Soda',
      name: 'Sugandhi Soda',
      shortDescription: 'A refreshing and fragrant veg soda to tantalize your taste buds with its delightful flavors.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 66,
    ),
    Product(
      sku: 'DSMW-067',
      categoryName: 'Soda',
      name: 'Grape Soda',
      shortDescription: 'Effervescent and fruity, this refreshing soda will tantalize your taste buds with its grape-infused delight.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 67,
    ),
    Product(
      sku: 'DSMW-068',
      categoryName: 'Lassi',
      name: 'Oreo Lassi',
      shortDescription: 'A creamy and indulgent treat that combines the classic flavors of Oreo cookies with the refreshing essence of a traditional lassi.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 9900,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 68,
    ),
    Product(
      sku: 'DSMW-069',
      categoryName: 'Lassi',
      name: 'Chocolate Lassi',
      shortDescription: 'Smooth, creamy and indulgent, this sweet treat is a chocolate lover\'s dream, blending rich cocoa flavors with the refreshing, velvety texture of traditional Lassi.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 69,
    ),
    Product(
      sku: 'DSMW-070',
      categoryName: 'Lassi',
      name: 'Strawberry Lassi',
      shortDescription: 'A refreshing and creamy fusion of strawberries, this lassi is a sweet delight that will brighten up your day.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 9900,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 70,
    ),
    Product(
      sku: 'DSMW-071',
      categoryName: 'Lassi',
      name: 'Sweet Vanilla',
      shortDescription: 'Indulge in a delectable, creamy delight bursting with the richness of vanilla essence, perfect for a refreshing lassi experience.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 71,
    ),
    Product(
      sku: 'DSMW-072',
      categoryName: 'Lassi',
      name: 'Thick Mango Lassi',
      shortDescription: 'Indulge in a luscious delight that combines the rich creaminess of lassi with the vibrant sweetness of ripe mangos, creating a thick and irresistible treat.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 72,
    ),
    Product(
      sku: 'DSMW-073',
      categoryName: 'Lassi',
      name: 'Special Dry Fruit Lassi',
      shortDescription: 'Indulge in a creamy, velvety delight loaded with the richness of dry fruits in every sip.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 73,
    ),
    Product(
      sku: 'DSMW-074',
      categoryName: 'Mocktails',
      name: 'Strawberry Moctail',
      shortDescription: 'Creamy and refreshing, this delightful flavored milk combines the sweetness of ripe strawberries with a luscious, smooth texture.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 74,
    ),
    Product(
      sku: 'DSMW-075',
      categoryName: 'Mocktails',
      name: 'Blue Curacao Moctail',
      shortDescription: 'A vibrant and refreshing mocktail bursting with tropical flavors, perfect for any occasion.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 75,
    ),
    Product(
      sku: 'DSMW-076',
      categoryName: 'Mocktails',
      name: 'Black Currant Mactail',
      shortDescription: 'Indulge in a tangy and refreshing black currant mocktail that will invigorate your taste buds.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 76,
    ),
    Product(
      sku: 'DSMW-077',
      categoryName: 'Mocktails',
      name: 'Mint Mactail',
      shortDescription: 'Refreshing and invigorating, this mocktail combines the cool essence of mint with a delightful blend of flavors, creating a truly delectable experience for your taste buds.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 77,
    ),
    Product(
      sku: 'DSMW-078',
      categoryName: 'Mocktails',
      name: 'Mint And Lime',
      shortDescription: 'Mint And Lime beverage or dessert from the mocktails menu.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: false,
      vegetarian: true,
      sortOrder: 78,
    ),
    Product(
      sku: 'DSMW-079',
      categoryName: 'Mocktails',
      name: 'Litchi',
      shortDescription: 'A refreshing and creamy blend of flavors make this indulgent treat the perfect way to cool down and satisfy your cravings.',
      sizeOrServing: 'Standard serving (size not published)',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 79,
    ),
  ];

  static StoreCatalog getCatalog() {
    return StoreCatalog(
      outlet: outlet,
      categories: categories,
      products: products,
    );
  }

  static Product? getProductBySku(String sku) {
    try {
      return products.firstWhere((p) => p.sku == sku);
    } catch (_) {
      return null;
    }
  }

  static void updateProductAvailability(String sku, bool availability) {
    final p = getProductBySku(sku);
    if (p != null) {
      p.availability = availability;
    }
  }

  static bool updateProductDetails({
    required String sku,
    int? pricePaise,
    int? offerPricePaise,
    bool? availability,
    bool? customisable,
    String? shortDescription,
  }) {
    final p = getProductBySku(sku);
    if (p == null) return false;
    if (pricePaise != null) p.pricePaise = pricePaise;
    p.offerPricePaise = offerPricePaise;
    if (availability != null) p.availability = availability;
    if (customisable != null) p.customisable = customisable;
    if (shortDescription != null) p.shortDescription = shortDescription;
    return true;
  }
}
