import 'package:ds_milk_world_client/ds_milk_world_client.dart';

class MockData {
  static final Outlet outlet = Outlet(
    name: 'DS Milk World',
    phone: '+91 866 254 9999',
    address: 'Near Kanuru Center, Bandar Road, Kanuru, Vijayawada, AP 520007',
    latitude: 16.4850,
    longitude: 80.6900,
    status: 'open',
    serviceRadiusM: 5000,
    timezone: 'Asia/Kolkata',
    openingTime: '10:00',
    closingTime: '23:00',
    minOrderPaise: 0,
    staffPin: '1979',
  );

  static final List<Category> categories = [
    Category(name: 'Butter Milk', slug: 'butter-milk', sortOrder: 1, published: true),
    Category(name: 'Lassi', slug: 'lassi', sortOrder: 2, published: true),
    Category(name: 'Mocktails', slug: 'mocktails', sortOrder: 3, published: true),
    Category(name: 'Falooda', slug: 'falooda', sortOrder: 4, published: true),
    Category(name: 'Soda', slug: 'soda', sortOrder: 5, published: true),
    Category(name: 'Shakes', slug: 'shakes', sortOrder: 6, published: true),
    Category(name: 'Our Specials', slug: 'our-specials', sortOrder: 7, published: true),
  ];

  static final List<Product> products = [
    Product(
      sku: 'DSMW-BM-01-300',
      categoryName: 'Butter Milk',
      name: 'Masala Butter Milk',
      shortDescription: 'Refreshing spiced buttermilk churned fresh with ginger, green chillies & curry leaves',
      sizeOrServing: '300ml',
      pricePaise: 2000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 1,
    ),
    Product(
      sku: 'DSMW-BM-01-500',
      categoryName: 'Butter Milk',
      name: 'Masala Butter Milk',
      shortDescription: 'Refreshing spiced buttermilk churned fresh with ginger, green chillies & curry leaves',
      sizeOrServing: '500ml',
      pricePaise: 3000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 2,
    ),
    Product(
      sku: 'DSMW-BM-01-1L',
      categoryName: 'Butter Milk',
      name: 'Masala Butter Milk',
      shortDescription: 'Refreshing spiced buttermilk churned fresh with ginger, green chillies & curry leaves',
      sizeOrServing: '1lt',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 3,
    ),
    Product(
      sku: 'DSMW-BM-02-300',
      categoryName: 'Butter Milk',
      name: 'Jeera Butter Milk',
      shortDescription: 'Traditional buttermilk infused with roasted jeera (cumin) seeds',
      sizeOrServing: '300ml',
      pricePaise: 2500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 4,
    ),
    Product(
      sku: 'DSMW-BM-02-500',
      categoryName: 'Butter Milk',
      name: 'Jeera Butter Milk',
      shortDescription: 'Traditional buttermilk infused with roasted jeera (cumin) seeds',
      sizeOrServing: '500ml',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 5,
    ),
    Product(
      sku: 'DSMW-BM-02-1L',
      categoryName: 'Butter Milk',
      name: 'Jeera Butter Milk',
      shortDescription: 'Traditional buttermilk infused with roasted jeera (cumin) seeds',
      sizeOrServing: '1lt',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 6,
    ),
    Product(
      sku: 'DSMW-BM-03-300',
      categoryName: 'Butter Milk',
      name: 'Lemon Butter Milk',
      shortDescription: 'Tangy and cooling churned buttermilk with fresh lime zest',
      sizeOrServing: '300ml',
      pricePaise: 2500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 7,
    ),
    Product(
      sku: 'DSMW-BM-03-500',
      categoryName: 'Butter Milk',
      name: 'Lemon Butter Milk',
      shortDescription: 'Tangy and cooling churned buttermilk with fresh lime zest',
      sizeOrServing: '500ml',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 8,
    ),
    Product(
      sku: 'DSMW-BM-03-1L',
      categoryName: 'Butter Milk',
      name: 'Lemon Butter Milk',
      shortDescription: 'Tangy and cooling churned buttermilk with fresh lime zest',
      sizeOrServing: '1lt',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 9,
    ),
    Product(
      sku: 'DSMW-BM-04-300',
      categoryName: 'Butter Milk',
      name: 'Lemon Sabja',
      shortDescription: 'Cooling lemon beverage loaded with soaked basil (sabja) seeds',
      sizeOrServing: '300ml',
      pricePaise: 2500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 10,
    ),
    Product(
      sku: 'DSMW-BM-04-500',
      categoryName: 'Butter Milk',
      name: 'Lemon Sabja',
      shortDescription: 'Cooling lemon beverage loaded with soaked basil (sabja) seeds',
      sizeOrServing: '500ml',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 11,
    ),
    Product(
      sku: 'DSMW-BM-04-1L',
      categoryName: 'Butter Milk',
      name: 'Lemon Sabja',
      shortDescription: 'Cooling lemon beverage loaded with soaked basil (sabja) seeds',
      sizeOrServing: '1lt',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 12,
    ),
    Product(
      sku: 'DSMW-BM-05-300',
      categoryName: 'Butter Milk',
      name: 'Jeera Sabja',
      shortDescription: 'Zesty cumin beverage infused with cooling sabja seeds',
      sizeOrServing: '300ml',
      pricePaise: 2500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 13,
    ),
    Product(
      sku: 'DSMW-BM-05-500',
      categoryName: 'Butter Milk',
      name: 'Jeera Sabja',
      shortDescription: 'Zesty cumin beverage infused with cooling sabja seeds',
      sizeOrServing: '500ml',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 14,
    ),
    Product(
      sku: 'DSMW-BM-05-1L',
      categoryName: 'Butter Milk',
      name: 'Jeera Sabja',
      shortDescription: 'Zesty cumin beverage infused with cooling sabja seeds',
      sizeOrServing: '1lt',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 15,
    ),
    Product(
      sku: 'DSMW-LAS-01-300ml',
      categoryName: 'Lassi',
      name: 'Sweet Lassi',
      shortDescription: 'Rich, thick and creamy Punjabi-style sweet lassi',
      sizeOrServing: '300ml',
      pricePaise: 3500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 16,
    ),
    Product(
      sku: 'DSMW-LAS-01-500ml',
      categoryName: 'Lassi',
      name: 'Sweet Lassi',
      shortDescription: 'Rich, thick and creamy Punjabi-style sweet lassi',
      sizeOrServing: '500ml',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 17,
    ),
    Product(
      sku: 'DSMW-LAS-01-1lt',
      categoryName: 'Lassi',
      name: 'Sweet Lassi',
      shortDescription: 'Rich, thick and creamy Punjabi-style sweet lassi',
      sizeOrServing: '1lt',
      pricePaise: 11000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 18,
    ),
    Product(
      sku: 'DSMW-LAS-02',
      categoryName: 'Lassi',
      name: 'Chocolate Lassi',
      shortDescription: 'Velvety sweet curd lassi blended with rich chocolate fudge',
      sizeOrServing: 'Standard serving',
      pricePaise: 7000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 19,
    ),
    Product(
      sku: 'DSMW-LAS-03',
      categoryName: 'Lassi',
      name: 'Oreo Lassi',
      shortDescription: 'Luscious creamy curd layered with crunchy crushed Oreo cookies',
      sizeOrServing: 'Standard serving',
      pricePaise: 7000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 20,
    ),
    Product(
      sku: 'DSMW-LAS-04',
      categoryName: 'Lassi',
      name: 'Strawberry Lassi',
      shortDescription: 'Sweet curd churned with aromatic fresh strawberry compote',
      sizeOrServing: 'Standard serving',
      pricePaise: 7000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 21,
    ),
    Product(
      sku: 'DSMW-LAS-05',
      categoryName: 'Lassi',
      name: 'Mango Lassi',
      shortDescription: 'Alphonso mango pulp whipped with rich creamy curd',
      sizeOrServing: 'Standard serving',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 22,
    ),
    Product(
      sku: 'DSMW-LAS-06',
      categoryName: 'Lassi',
      name: 'Dry Fruit Lassi',
      shortDescription: 'Royal lassi enriched with chopped cashews, almonds, and pistachios',
      sizeOrServing: 'Standard serving',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 23,
    ),
    Product(
      sku: 'DSMW-MOK-01',
      categoryName: 'Mocktails',
      name: 'Blue Curacao',
      shortDescription: 'Vibrant citrus blue cooler with sparkling soda & mint',
      sizeOrServing: 'Standard glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 24,
    ),
    Product(
      sku: 'DSMW-MOK-02',
      categoryName: 'Mocktails',
      name: 'Mint & Lime',
      shortDescription: 'Crisp garden fresh mint muddled with tangy lime',
      sizeOrServing: 'Standard glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 25,
    ),
    Product(
      sku: 'DSMW-MOK-03',
      categoryName: 'Mocktails',
      name: 'Black Currant',
      shortDescription: 'Rich and zesty wild black currant sparkling mocktail',
      sizeOrServing: 'Standard glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 26,
    ),
    Product(
      sku: 'DSMW-MOK-04',
      categoryName: 'Mocktails',
      name: 'Strawberry Mocktail',
      shortDescription: 'Fruity sparkling cooler with sweet strawberry bliss',
      sizeOrServing: 'Standard glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 27,
    ),
    Product(
      sku: 'DSMW-MOK-05',
      categoryName: 'Mocktails',
      name: 'Mint Mocktail',
      shortDescription: 'Ultra refreshing pure mint crushed ice cooler',
      sizeOrServing: 'Standard glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 28,
    ),
    Product(
      sku: 'DSMW-MOK-06',
      categoryName: 'Mocktails',
      name: 'Litchi Mocktail',
      shortDescription: 'Exotic tropical litchi sparkling beverage',
      sizeOrServing: 'Standard glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 29,
    ),
    Product(
      sku: 'DSMW-FAL-01',
      categoryName: 'Falooda',
      name: 'Rose Falooda',
      shortDescription: 'Traditional rose syrup, vermicelli, sabja seeds, chilled milk & vanilla ice cream',
      sizeOrServing: 'Standard serving',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 30,
    ),
    Product(
      sku: 'DSMW-FAL-02',
      categoryName: 'Falooda',
      name: 'Chocolate Falooda',
      shortDescription: 'Decadent chocolate syrup, falooda sev, sabja and chocolate ice cream scoop',
      sizeOrServing: 'Standard serving',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 31,
    ),
    Product(
      sku: 'DSMW-FAL-03',
      categoryName: 'Falooda',
      name: 'Pista Falooda',
      shortDescription: 'Aromatic pistachio flavored falooda layered with nuts and creamy pista ice cream',
      sizeOrServing: 'Standard serving',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 32,
    ),
    Product(
      sku: 'DSMW-FAL-04',
      categoryName: 'Falooda',
      name: 'Mango Falooda',
      shortDescription: 'Alphonso mango pulp layered with falooda noodles and mango ice cream',
      sizeOrServing: 'Standard serving',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 33,
    ),
    Product(
      sku: 'DSMW-FAL-05',
      categoryName: 'Falooda',
      name: 'Oreo Falooda',
      shortDescription: 'Crunchy Oreo biscuit layers with chilled dairy cream and vanilla scoop',
      sizeOrServing: 'Standard serving',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 34,
    ),
    Product(
      sku: 'DSMW-FAL-06',
      categoryName: 'Falooda',
      name: 'Tender Coconut Falooda',
      shortDescription: 'Fresh tender coconut malai puree with jelly, noodles and rich cream',
      sizeOrServing: 'Standard serving',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 35,
    ),
    Product(
      sku: 'DSMW-FAL-07',
      categoryName: 'Falooda',
      name: 'Badam Falooda',
      shortDescription: 'Luscious badam milk blend topped with sliced almonds and dairy scoop',
      sizeOrServing: 'Standard serving',
      pricePaise: 12000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 36,
    ),
    Product(
      sku: 'DSMW-FAL-08',
      categoryName: 'Falooda',
      name: 'Fruit Punch Falooda',
      shortDescription: 'Assorted tropical fresh fruits mixed with falooda sev and double scoop',
      sizeOrServing: 'Standard serving',
      pricePaise: 12000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 37,
    ),
    Product(
      sku: 'DSMW-FAL-09',
      categoryName: 'Falooda',
      name: 'Kulfi Falooda',
      shortDescription: 'Authentic sliced malai kulfi served over chilled rabri, rose & falooda sev',
      sizeOrServing: 'Standard serving',
      pricePaise: 12000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 38,
    ),
    Product(
      sku: 'DSMW-FAL-10',
      categoryName: 'Falooda',
      name: 'Dry Fruit Falooda',
      shortDescription: 'Loaded with roasted cashews, badam, raisins, pista & rich cream',
      sizeOrServing: 'Standard serving',
      pricePaise: 12000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 39,
    ),
    Product(
      sku: 'DSMW-FAL-11',
      categoryName: 'Falooda',
      name: 'Sp. Dry Fruit Falooda',
      shortDescription: 'The ultimate royal falooda loaded with exotic dry fruits, saffron & double ice cream',
      sizeOrServing: 'Standard serving',
      pricePaise: 19000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 40,
    ),
    Product(
      sku: 'DSMW-SOD-01',
      categoryName: 'Soda',
      name: 'Sweet & Lime Soda',
      shortDescription: 'Refreshing chilled fizzy soda with sweet syrup and freshly squeezed lime',
      sizeOrServing: 'Standard glass',
      pricePaise: 3000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 41,
    ),
    Product(
      sku: 'DSMW-SOD-02',
      categoryName: 'Soda',
      name: 'Salt & Lime Soda',
      shortDescription: 'Crisp and hydrating soda with rock salt and lemon',
      sizeOrServing: 'Standard glass',
      pricePaise: 3000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 42,
    ),
    Product(
      sku: 'DSMW-SOD-03',
      categoryName: 'Soda',
      name: 'Jeera Soda',
      shortDescription: 'Digestive fizzy soda bursting with roasted cumin spice',
      sizeOrServing: 'Standard glass',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 43,
    ),
    Product(
      sku: 'DSMW-SOD-04',
      categoryName: 'Soda',
      name: 'Cola Soda',
      shortDescription: 'Classic chilled sparkling cola soda fountain refresher',
      sizeOrServing: 'Standard glass',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 44,
    ),
    Product(
      sku: 'DSMW-SOD-05',
      categoryName: 'Soda',
      name: 'Orange Soda',
      shortDescription: 'Tangy citrus orange fizzy soda',
      sizeOrServing: 'Standard glass',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 45,
    ),
    Product(
      sku: 'DSMW-SOD-06',
      categoryName: 'Soda',
      name: 'Grape Soda',
      shortDescription: 'Sweet dark grape fizzy soda refresher',
      sizeOrServing: 'Standard glass',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 46,
    ),
    Product(
      sku: 'DSMW-SOD-07',
      categoryName: 'Soda',
      name: 'Sugandhi Soda',
      shortDescription: 'Traditional cooling nannari / sugandhi root syrup with sparkling soda',
      sizeOrServing: 'Standard glass',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 47,
    ),
    Product(
      sku: 'DSMW-SHK-01-M',
      categoryName: 'Shakes',
      name: 'Vanilla Shake',
      shortDescription: 'Classic rich Madagascar vanilla blend with creamy dairy',
      sizeOrServing: 'Milk Shake',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 48,
    ),
    Product(
      sku: 'DSMW-SHK-01-T',
      categoryName: 'Shakes',
      name: 'Vanilla Shake',
      shortDescription: 'Classic rich Madagascar vanilla blend with creamy dairy',
      sizeOrServing: 'Thick Shake',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 49,
    ),
    Product(
      sku: 'DSMW-SHK-02-M',
      categoryName: 'Shakes',
      name: 'Strawberry Shake',
      shortDescription: 'Luscious pink strawberry puree blended with fresh dairy',
      sizeOrServing: 'Milk Shake',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 50,
    ),
    Product(
      sku: 'DSMW-SHK-02-T',
      categoryName: 'Shakes',
      name: 'Strawberry Shake',
      shortDescription: 'Luscious pink strawberry puree blended with fresh dairy',
      sizeOrServing: 'Thick Shake',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 51,
    ),
    Product(
      sku: 'DSMW-SHK-03-M',
      categoryName: 'Shakes',
      name: 'Vanilla Strawberry Shake',
      shortDescription: 'Dual fusion of fragrant vanilla and sweet berry swirl',
      sizeOrServing: 'Milk Shake',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 52,
    ),
    Product(
      sku: 'DSMW-SHK-03-T',
      categoryName: 'Shakes',
      name: 'Vanilla Strawberry Shake',
      shortDescription: 'Dual fusion of fragrant vanilla and sweet berry swirl',
      sizeOrServing: 'Thick Shake',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 53,
    ),
    Product(
      sku: 'DSMW-SHK-04-M',
      categoryName: 'Shakes',
      name: 'Pista Shake',
      shortDescription: 'Rich nutty pistachio shake garnished with crushed nuts',
      sizeOrServing: 'Milk Shake',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 54,
    ),
    Product(
      sku: 'DSMW-SHK-04-T',
      categoryName: 'Shakes',
      name: 'Pista Shake',
      shortDescription: 'Rich nutty pistachio shake garnished with crushed nuts',
      sizeOrServing: 'Thick Shake',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 55,
    ),
    Product(
      sku: 'DSMW-SHK-05-M',
      categoryName: 'Shakes',
      name: 'Vanilla Pista Shake',
      shortDescription: 'Silky vanilla blend accented with green pista essence',
      sizeOrServing: 'Milk Shake',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 56,
    ),
    Product(
      sku: 'DSMW-SHK-05-T',
      categoryName: 'Shakes',
      name: 'Vanilla Pista Shake',
      shortDescription: 'Silky vanilla blend accented with green pista essence',
      sizeOrServing: 'Thick Shake',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 57,
    ),
    Product(
      sku: 'DSMW-SHK-06-M',
      categoryName: 'Shakes',
      name: 'Strawberry Oreo Shake',
      shortDescription: 'Sweet strawberry cream mixed with crunchy chocolate cookie bits',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 58,
    ),
    Product(
      sku: 'DSMW-SHK-06-T',
      categoryName: 'Shakes',
      name: 'Strawberry Oreo Shake',
      shortDescription: 'Sweet strawberry cream mixed with crunchy chocolate cookie bits',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 59,
    ),
    Product(
      sku: 'DSMW-SHK-07-M',
      categoryName: 'Shakes',
      name: 'Black Currant Shake',
      shortDescription: 'Deep berry punch with real black currant syrup and cream',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 60,
    ),
    Product(
      sku: 'DSMW-SHK-07-T',
      categoryName: 'Shakes',
      name: 'Black Currant Shake',
      shortDescription: 'Deep berry punch with real black currant syrup and cream',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 61,
    ),
    Product(
      sku: 'DSMW-SHK-08-M',
      categoryName: 'Shakes',
      name: 'Mango Shake',
      shortDescription: 'Sunshine alphonso mango shake made with thick dairy milk',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 62,
    ),
    Product(
      sku: 'DSMW-SHK-08-T',
      categoryName: 'Shakes',
      name: 'Mango Shake',
      shortDescription: 'Sunshine alphonso mango shake made with thick dairy milk',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 63,
    ),
    Product(
      sku: 'DSMW-SHK-09-M',
      categoryName: 'Shakes',
      name: 'Butter Scotch Shake',
      shortDescription: 'Crunchy butterscotch praline caramel crunch shake',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 64,
    ),
    Product(
      sku: 'DSMW-SHK-09-T',
      categoryName: 'Shakes',
      name: 'Butter Scotch Shake',
      shortDescription: 'Crunchy butterscotch praline caramel crunch shake',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 65,
    ),
    Product(
      sku: 'DSMW-SHK-10-M',
      categoryName: 'Shakes',
      name: 'Chocolate Shake',
      shortDescription: 'Rich cocoa indulgence blended smooth and thick',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 66,
    ),
    Product(
      sku: 'DSMW-SHK-10-T',
      categoryName: 'Shakes',
      name: 'Chocolate Shake',
      shortDescription: 'Rich cocoa indulgence blended smooth and thick',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 67,
    ),
    Product(
      sku: 'DSMW-SHK-11-M',
      categoryName: 'Shakes',
      name: 'Oreo Shake',
      shortDescription: 'The crowd favorite: crushed chocolate Oreos with thick ice cream',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 68,
    ),
    Product(
      sku: 'DSMW-SHK-11-T',
      categoryName: 'Shakes',
      name: 'Oreo Shake',
      shortDescription: 'The crowd favorite: crushed chocolate Oreos with thick ice cream',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 69,
    ),
    Product(
      sku: 'DSMW-SHK-12-M',
      categoryName: 'Shakes',
      name: 'Kitkat Shake',
      shortDescription: 'Crispy KitKat wafer bars blended into rich milk chocolate',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 70,
    ),
    Product(
      sku: 'DSMW-SHK-12-T',
      categoryName: 'Shakes',
      name: 'Kitkat Shake',
      shortDescription: 'Crispy KitKat wafer bars blended into rich milk chocolate',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 71,
    ),
    Product(
      sku: 'DSMW-SHK-13-M',
      categoryName: 'Shakes',
      name: 'Dark Fantasy Shake',
      shortDescription: 'Indulgent molten choco-fill cookies whipped into decadent shake',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 72,
    ),
    Product(
      sku: 'DSMW-SHK-13-T',
      categoryName: 'Shakes',
      name: 'Dark Fantasy Shake',
      shortDescription: 'Indulgent molten choco-fill cookies whipped into decadent shake',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 73,
    ),
    Product(
      sku: 'DSMW-SHK-14-M',
      categoryName: 'Shakes',
      name: 'Perk Shake',
      shortDescription: 'Light chocolate wafer Perk pieces whipped with chilled dairy',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 74,
    ),
    Product(
      sku: 'DSMW-SHK-14-T',
      categoryName: 'Shakes',
      name: 'Perk Shake',
      shortDescription: 'Light chocolate wafer Perk pieces whipped with chilled dairy',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 75,
    ),
    Product(
      sku: 'DSMW-SHK-15-M',
      categoryName: 'Shakes',
      name: 'Munch Shake',
      shortDescription: 'Crunchy Nestle Munch chocolate crunch shake',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 76,
    ),
    Product(
      sku: 'DSMW-SHK-15-T',
      categoryName: 'Shakes',
      name: 'Munch Shake',
      shortDescription: 'Crunchy Nestle Munch chocolate crunch shake',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 77,
    ),
    Product(
      sku: 'DSMW-SHK-16-M',
      categoryName: 'Shakes',
      name: '5 Star Shake',
      shortDescription: 'Chewy caramel and nougat 5 Star chocolate sensation',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 78,
    ),
    Product(
      sku: 'DSMW-SHK-16-T',
      categoryName: 'Shakes',
      name: '5 Star Shake',
      shortDescription: 'Chewy caramel and nougat 5 Star chocolate sensation',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 79,
    ),
    Product(
      sku: 'DSMW-SHK-17-M',
      categoryName: 'Shakes',
      name: 'Gems Shake',
      shortDescription: 'Colorful Cadbury Gems blended into a sweet fun dairy shake',
      sizeOrServing: 'Milk Shake',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 80,
    ),
    Product(
      sku: 'DSMW-SHK-17-T',
      categoryName: 'Shakes',
      name: 'Gems Shake',
      shortDescription: 'Colorful Cadbury Gems blended into a sweet fun dairy shake',
      sizeOrServing: 'Thick Shake',
      pricePaise: 14000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 81,
    ),
    Product(
      sku: 'DSMW-SHK-18-M',
      categoryName: 'Shakes',
      name: 'Butter Choco Shake',
      shortDescription: 'Buttery caramel toffee paired with rich milk chocolate',
      sizeOrServing: 'Milk Shake',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 82,
    ),
    Product(
      sku: 'DSMW-SHK-18-T',
      categoryName: 'Shakes',
      name: 'Butter Choco Shake',
      shortDescription: 'Buttery caramel toffee paired with rich milk chocolate',
      sizeOrServing: 'Thick Shake',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 83,
    ),
    Product(
      sku: 'DSMW-SHK-19-M',
      categoryName: 'Shakes',
      name: 'Oreo Chocolate Shake',
      shortDescription: 'Double chocolate explosion with Oreos and dark chocolate sauce',
      sizeOrServing: 'Milk Shake',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 84,
    ),
    Product(
      sku: 'DSMW-SHK-19-T',
      categoryName: 'Shakes',
      name: 'Oreo Chocolate Shake',
      shortDescription: 'Double chocolate explosion with Oreos and dark chocolate sauce',
      sizeOrServing: 'Thick Shake',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 85,
    ),
    Product(
      sku: 'DSMW-SHK-20-M',
      categoryName: 'Shakes',
      name: 'Oreo Caramel Shake',
      shortDescription: 'Oreos combined with buttery golden caramel swirl',
      sizeOrServing: 'Milk Shake',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 86,
    ),
    Product(
      sku: 'DSMW-SHK-20-T',
      categoryName: 'Shakes',
      name: 'Oreo Caramel Shake',
      shortDescription: 'Oreos combined with buttery golden caramel swirl',
      sizeOrServing: 'Thick Shake',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 87,
    ),
    Product(
      sku: 'DSMW-SHK-21-M',
      categoryName: 'Shakes',
      name: 'Caramel Shake',
      shortDescription: 'Smooth golden salted caramel cream delight',
      sizeOrServing: 'Milk Shake',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 88,
    ),
    Product(
      sku: 'DSMW-SHK-21-T',
      categoryName: 'Shakes',
      name: 'Caramel Shake',
      shortDescription: 'Smooth golden salted caramel cream delight',
      sizeOrServing: 'Thick Shake',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 89,
    ),
    Product(
      sku: 'DSMW-SHK-22-M',
      categoryName: 'Shakes',
      name: 'Caramel Kitkat Shake',
      shortDescription: 'Wafer crunch of KitKat infused with silky warm caramel',
      sizeOrServing: 'Milk Shake',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 90,
    ),
    Product(
      sku: 'DSMW-SHK-22-T',
      categoryName: 'Shakes',
      name: 'Caramel Kitkat Shake',
      shortDescription: 'Wafer crunch of KitKat infused with silky warm caramel',
      sizeOrServing: 'Thick Shake',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 91,
    ),
    Product(
      sku: 'DSMW-SHK-23-M',
      categoryName: 'Shakes',
      name: 'Choco Chip Shake',
      shortDescription: 'Loaded with dark chocolate chips that crunch in every sip',
      sizeOrServing: 'Milk Shake',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 92,
    ),
    Product(
      sku: 'DSMW-SHK-23-T',
      categoryName: 'Shakes',
      name: 'Choco Chip Shake',
      shortDescription: 'Loaded with dark chocolate chips that crunch in every sip',
      sizeOrServing: 'Thick Shake',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 93,
    ),
    Product(
      sku: 'DSMW-SHK-24-M',
      categoryName: 'Shakes',
      name: 'Belgium Dark Shake',
      shortDescription: 'Intense 70% dark Belgian cocoa indulgence for true chocolate lovers',
      sizeOrServing: 'Milk Shake',
      pricePaise: 10000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 94,
    ),
    Product(
      sku: 'DSMW-SHK-24-T',
      categoryName: 'Shakes',
      name: 'Belgium Dark Shake',
      shortDescription: 'Intense 70% dark Belgian cocoa indulgence for true chocolate lovers',
      sizeOrServing: 'Thick Shake',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 95,
    ),
    Product(
      sku: 'DSMW-SHK-25-M',
      categoryName: 'Shakes',
      name: 'Dry Fruit Shake',
      shortDescription: 'Loaded with almonds, cashews, pistachios and figs',
      sizeOrServing: 'Milk Shake',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 96,
    ),
    Product(
      sku: 'DSMW-SHK-25-T',
      categoryName: 'Shakes',
      name: 'Dry Fruit Shake',
      shortDescription: 'Loaded with almonds, cashews, pistachios and figs',
      sizeOrServing: 'Thick Shake',
      pricePaise: 20000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 97,
    ),
    Product(
      sku: 'DSMW-SHK-26-M',
      categoryName: 'Shakes',
      name: 'Tender Coconut Shake',
      shortDescription: 'Silky natural coconut malai puree blended fresh and thick',
      sizeOrServing: 'Milk Shake',
      pricePaise: 13000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 98,
    ),
    Product(
      sku: 'DSMW-SHK-26-T',
      categoryName: 'Shakes',
      name: 'Tender Coconut Shake',
      shortDescription: 'Silky natural coconut malai puree blended fresh and thick',
      sizeOrServing: 'Thick Shake',
      pricePaise: 20000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 99,
    ),
    Product(
      sku: 'DSMW-SPC-01-250ml',
      categoryName: 'Our Specials',
      name: 'Lemonade',
      shortDescription: 'Chilled thirst-quenching fresh lemon drink',
      sizeOrServing: '250ml',
      pricePaise: 2000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 122,
    ),
    Product(
      sku: 'DSMW-SPC-01-500ml',
      categoryName: 'Our Specials',
      name: 'Lemonade',
      shortDescription: 'Chilled thirst-quenching fresh lemon drink',
      sizeOrServing: '500ml',
      pricePaise: 3000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 123,
    ),
    Product(
      sku: 'DSMW-SPC-01-1lt',
      categoryName: 'Our Specials',
      name: 'Lemonade',
      shortDescription: 'Chilled thirst-quenching fresh lemon drink',
      sizeOrServing: '1lt',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 124,
    ),
    Product(
      sku: 'DSMW-SPC-02-250ml',
      categoryName: 'Our Specials',
      name: 'Sabja Lemonade',
      shortDescription: 'Cooling lemonade enriched with soaked sweet basil seeds',
      sizeOrServing: '250ml',
      pricePaise: 2500,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 125,
    ),
    Product(
      sku: 'DSMW-SPC-02-500ml',
      categoryName: 'Our Specials',
      name: 'Sabja Lemonade',
      shortDescription: 'Cooling lemonade enriched with soaked sweet basil seeds',
      sizeOrServing: '500ml',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 126,
    ),
    Product(
      sku: 'DSMW-SPC-02-1lt',
      categoryName: 'Our Specials',
      name: 'Sabja Lemonade',
      shortDescription: 'Cooling lemonade enriched with soaked sweet basil seeds',
      sizeOrServing: '1lt',
      pricePaise: 6000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 127,
    ),
    Product(
      sku: 'DSMW-SPC-03-250ml',
      categoryName: 'Our Specials',
      name: 'Pulpy Grape',
      shortDescription: 'Famous Vijayawada special real crushed dark grape juice with whole pulp',
      sizeOrServing: '250ml',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 128,
    ),
    Product(
      sku: 'DSMW-SPC-03-500ml',
      categoryName: 'Our Specials',
      name: 'Pulpy Grape',
      shortDescription: 'Famous Vijayawada special real crushed dark grape juice with whole pulp',
      sizeOrServing: '500ml',
      pricePaise: 8000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 129,
    ),
    Product(
      sku: 'DSMW-SPC-03-1lt',
      categoryName: 'Our Specials',
      name: 'Pulpy Grape',
      shortDescription: 'Famous Vijayawada special real crushed dark grape juice with whole pulp',
      sizeOrServing: '1lt',
      pricePaise: 15000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 130,
    ),
    Product(
      sku: 'DSMW-SPC-04-250ml',
      categoryName: 'Our Specials',
      name: 'Badam Milk',
      shortDescription: 'Traditional slow-simmered whole dairy milk infused with almonds and saffron',
      sizeOrServing: '250ml',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 131,
    ),
    Product(
      sku: 'DSMW-SPC-04-500ml',
      categoryName: 'Our Specials',
      name: 'Badam Milk',
      shortDescription: 'Traditional slow-simmered whole dairy milk infused with almonds and saffron',
      sizeOrServing: '500ml',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 132,
    ),
    Product(
      sku: 'DSMW-SPC-04-1lt',
      categoryName: 'Our Specials',
      name: 'Badam Milk',
      shortDescription: 'Traditional slow-simmered whole dairy milk infused with almonds and saffron',
      sizeOrServing: '1lt',
      pricePaise: 18000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 133,
    ),
    Product(
      sku: 'DSMW-SPC-05',
      categoryName: 'Our Specials',
      name: 'Pista Milk',
      shortDescription: 'Fragrant green pistachio chilled milk with ground nuts',
      sizeOrServing: '250ml Glass',
      pricePaise: 4000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 134,
    ),
    Product(
      sku: 'DSMW-SPC-06',
      categoryName: 'Our Specials',
      name: 'Fruit Punch Special',
      shortDescription: 'Signature mixed fruit chilled dairy beverage',
      sizeOrServing: '250ml Glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 135,
    ),
    Product(
      sku: 'DSMW-SPC-07',
      categoryName: 'Our Specials',
      name: 'Rose Milk',
      shortDescription: 'Classic chilled dairy drink with pure rose petal syrup',
      sizeOrServing: '250ml Glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 136,
    ),
    Product(
      sku: 'DSMW-SPC-08',
      categoryName: 'Our Specials',
      name: 'SP Badam Milk',
      shortDescription: 'Ultra-rich special badam milk with double roasted almond slivers & malai',
      sizeOrServing: '250ml Glass',
      pricePaise: 9000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 137,
    ),
    Product(
      sku: 'DSMW-SPC-09',
      categoryName: 'Our Specials',
      name: 'Cold Coffee',
      shortDescription: 'Frothy blended cafe-style espresso cold coffee with ice cream creaminess',
      sizeOrServing: '250ml Glass',
      pricePaise: 5000,
      offerPricePaise: null,
      availability: true,
      customisable: true,
      vegetarian: true,
      sortOrder: 138,
    ),
  ];

  static StoreCatalog getCatalog() {
    return StoreCatalog(
      outlet: outlet,
      categories: categories,
      products: products,
    );
  }

  static Product? getProductBySku(String sku) {
    try {
      return products.firstWhere((p) => p.sku == sku);
    } catch (_) {
      return null;
    }
  }

  static bool updateProductAvailability(String sku, bool availability) {
    final index = products.indexWhere((p) => p.sku == sku);
    if (index >= 0) {
      products[index] = Product(
        id: products[index].id,
        sku: products[index].sku,
        categoryName: products[index].categoryName,
        name: products[index].name,
        shortDescription: products[index].shortDescription,
        sizeOrServing: products[index].sizeOrServing,
        pricePaise: products[index].pricePaise,
        offerPricePaise: products[index].offerPricePaise,
        availability: availability,
        customisable: products[index].customisable,
        vegetarian: products[index].vegetarian,
        sortOrder: products[index].sortOrder,
      );
      return true;
    }
    return false;
  }

  static bool updateProductDetails({
    required String sku,
    int? pricePaise,
    int? offerPricePaise,
    bool? availability,
    bool? customisable,
    String? shortDescription,
  }) {
    final index = products.indexWhere((p) => p.sku == sku);
    if (index >= 0) {
      final p = products[index];
      products[index] = Product(
        id: p.id,
        sku: p.sku,
        categoryName: p.categoryName,
        name: p.name,
        shortDescription: shortDescription ?? p.shortDescription,
        sizeOrServing: p.sizeOrServing,
        pricePaise: pricePaise ?? p.pricePaise,
        offerPricePaise: offerPricePaise ?? p.offerPricePaise,
        availability: availability ?? p.availability,
        customisable: customisable ?? p.customisable,
        vegetarian: p.vegetarian,
        sortOrder: p.sortOrder,
      );
      return true;
    }
    return false;
  }
}
