/// Product image assets scraped from Swiggy/Zomato for DS Milk World.
// Keys are exact product names from MockData; values are asset paths.
class ProductImages {
  ProductImages._();

  static const Map<String, String> byName = {
    '5 Star Shake': 'assets/images/products/shakes/bourbon-milk-shake.jpg',
    'Badam Falooda': 'assets/images/products/falooda/badam-falooda.jpg',
    'Badam Milk': 'assets/images/products/our-specials/badam-milk.jpg',
    'Belgium Dark Shake': 'assets/images/products/shakes/dark-fantasy-thick-shake.jpg',
    'Black Currant': 'assets/images/products/falooda/fruit-punch-falooda.jpg',
    'Black Currant Shake': 'assets/images/products/falooda/fruit-punch-falooda.jpg',
    'Blue Curacao': 'assets/images/products/mocktails/mint-and-lime.jpg',
    'Butter Choco Shake': 'assets/images/products/shakes/choco-fun-thick-shake.jpg',
    'Butter Scotch Shake': 'assets/images/products/shakes/caramel-thick-shake.jpg',
    'Caramel Kitkat Shake': 'assets/images/products/shakes/caramel-thick-shake.jpg',
    'Caramel Shake': 'assets/images/products/shakes/caramel-thick-shake.jpg',
    'Choco Chip Shake': 'assets/images/products/shakes/choco-fun-thick-shake.jpg',
    'Chocolate Falooda': 'assets/images/products/falooda/badam-falooda.jpg',
    'Chocolate Lassi': 'assets/images/products/our-specials/pista-milk.jpg',
    'Chocolate Shake': 'assets/images/products/shakes/choco-fun-thick-shake.jpg',
    'Cola Soda': 'assets/images/products/mocktails/mint-and-lime.jpg',
    'Cold Coffee': 'assets/images/products/our-specials/badam-milk.jpg',
    'Dark Fantasy Shake': 'assets/images/products/shakes/dark-fantasy-thick-shake.jpg',
    'Dry Fruit Falooda': 'assets/images/products/falooda/dry-fruit-falooda.jpg',
    'Dry Fruit Lassi': 'assets/images/products/our-specials/badam-milk.jpg',
    'Dry Fruit Shake': 'assets/images/products/shakes/dark-fantasy-thick-shake.jpg',
    'Fruit Punch Falooda': 'assets/images/products/falooda/fruit-punch-falooda.jpg',
    'Fruit Punch Special': 'assets/images/products/falooda/fruit-punch-falooda.jpg',
    'Gems Shake': 'assets/images/products/shakes/choco-fun-thick-shake.jpg',
    'Grape Soda': 'assets/images/products/our-specials/pulpy-grape.jpg',
    'Jeera Butter Milk': 'assets/images/products/butter-milk/special-jeera-masala.jpg',
    'Jeera Sabja': 'assets/images/products/butter-milk/special-jeera-masala.jpg',
    'Jeera Soda': 'assets/images/products/butter-milk/special-jeera-masala.jpg',
    'Kitkat Shake': 'assets/images/products/shakes/kitkat-milk-shake.jpg',
    'Kulfi Falooda': 'assets/images/products/falooda/badam-falooda.jpg',
    'Lemon Butter Milk': 'assets/images/products/butter-milk/special-lemon-masala.jpg',
    'Lemon Sabja': 'assets/images/products/butter-milk/special-lemon-masala.jpg',
    'Lemonade': 'assets/images/products/our-specials/lemonade.jpg',
    'Litchi Mocktail': 'assets/images/products/falooda/fruit-punch-falooda.jpg',
    'Mango Falooda': 'assets/images/products/falooda/fruit-punch-falooda.jpg',
    'Mango Lassi': 'assets/images/products/our-specials/pulpy-grape.jpg',
    'Mango Shake': 'assets/images/products/our-specials/pulpy-grape.jpg',
    'Masala Butter Milk': 'assets/images/products/butter-milk/masala-buttermilk.jpg',
    'Mint & Lime': 'assets/images/products/mocktails/mint-and-lime.jpg',
    'Mint Mocktail': 'assets/images/products/mocktails/mint-and-lime.jpg',
    'Munch Shake': 'assets/images/products/shakes/perk-thick-shake.jpg',
    'Orange Soda': 'assets/images/products/mocktails/mint-and-lime.jpg',
    'Oreo Caramel Shake': 'assets/images/products/shakes/oreo-milk-shake.jpg',
    'Oreo Chocolate Shake': 'assets/images/products/shakes/oreo-milk-shake.jpg',
    'Oreo Falooda': 'assets/images/products/falooda/dry-fruit-falooda.jpg',
    'Oreo Lassi': 'assets/images/products/shakes/oreo-milk-shake.jpg',
    'Oreo Shake': 'assets/images/products/shakes/oreo-milk-shake.jpg',
    'Perk Shake': 'assets/images/products/shakes/perk-thick-shake.jpg',
    'Pista Falooda': 'assets/images/products/falooda/dry-fruit-falooda.jpg',
    'Pista Milk': 'assets/images/products/our-specials/pista-milk.jpg',
    'Pista Shake': 'assets/images/products/our-specials/pista-milk.jpg',
    'Pulpy Grape': 'assets/images/products/our-specials/pulpy-grape.jpg',
    'Rose Falooda': 'assets/images/products/falooda/fruit-punch-falooda.jpg',
    'Rose Milk': 'assets/images/products/our-specials/rose-milk.jpg',
    'SP Badam Milk': 'assets/images/products/our-specials/badam-milk.jpg',
    'Sabja Lemonade': 'assets/images/products/butter-milk/special-lemon-masala.jpg',
    'Salt & Lime Soda': 'assets/images/products/mocktails/mint-and-lime.jpg',
    'Sp. Dry Fruit Falooda': 'assets/images/products/falooda/dry-fruit-falooda.jpg',
    'Strawberry Lassi': 'assets/images/products/our-specials/rose-milk.jpg',
    'Strawberry Mocktail': 'assets/images/products/our-specials/rose-milk.jpg',
    'Strawberry Oreo Shake': 'assets/images/products/shakes/oreo-milk-shake.jpg',
    'Strawberry Shake': 'assets/images/products/our-specials/rose-milk.jpg',
    'Sugandhi Soda': 'assets/images/products/butter-milk/special-lemon-masala.jpg',
    'Sweet & Lime Soda': 'assets/images/products/mocktails/mint-and-lime.jpg',
    'Sweet Lassi': 'assets/images/products/our-specials/pista-milk.jpg',
    'Tender Coconut Falooda': 'assets/images/products/falooda/badam-falooda.jpg',
    'Tender Coconut Shake': 'assets/images/products/our-specials/pista-milk.jpg',
    'Vanilla Pista Shake': 'assets/images/products/our-specials/pista-milk.jpg',
    'Vanilla Shake': 'assets/images/products/shakes/caramel-thick-shake.jpg',
    'Vanilla Strawberry Shake': 'assets/images/products/our-specials/rose-milk.jpg',
  };

  static String? forName(String? name) {
    if (name == null || name.isEmpty) return null;
    return byName[name];
  }
}
